### ISSUE TITLE
Collapse/Expand Icons Incorrect

### ISSUE THREAD

**Issue by BobWag12** [moodleou/moodle-report_customsql#158]
Updated to Moodle 4.5 and the category Collapse/Expand Icons for this plugin are no longer the nice small arrow.  They now now oversized black arrows and look terrible.  Aside from that, the plugin still appears to work with no issues.  I tried to modify the Collapse/Expand Icon myself, but do not understand where it is defined for this plugin.   If some when can tell me, perhaps I can correct this?

**Comment by sharpchi** [comment]
If you update the `styles.css` file in the plugin and set the background size you can resize it. Something like
```css
.csql_category.csql_categoryhidden .categoryname {
    background-image: url([[pix:moodle|t/collapsed]]);
    background-repeat: no-repeat;
    background-position: center left;
    background-size: .5em;
}
.csql_category.csql_categoryshown .categoryname {
    background-image: url([[pix:moodle|t/expanded]]);
    background-repeat: no-repeat;
    background-position: center left;
    background-size: .5em;
}
```
It appears Moodle fixed an [SVG browser compatibility issue](https://github.com/moodle/moodle/commit/e6ea778c030f496083a66ff7bc4273829b4b4409) that may have changed the underlying icon size.
